CREATE TABLE roles(
    role_id BIGSERIAL,
    name VARCHAR(15) NOT NULL,
    enabled BOOLEAN DEFAULT TRUE,
    deleted BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP,
    modified_at  TIMESTAMP,
    CONSTRAINT roles_pkey PRIMARY KEY(role_id),
    UNIQUE(name)
);

CREATE TABLE users(
    user_id BIGSERIAL,
    role_id BIGINT,
    firstname VARCHAR(30) NOT NULL,
    lastname VARCHAR(30) NOT NULL,
    password VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL,
    created_at TIMESTAMP,
    modified_at TIMESTAMP,
    last_login TIMESTAMP,
    enabled BOOLEAN DEFAULT true,
    deleted BOOLEAN DEFAULT false,
    CONSTRAINT FK_users_roles
    FOREIGN KEY (role_id) REFERENCES roles(role_id),
    CONSTRAINT users_pkey PRIMARY KEY(user_id),
    UNIQUE(email)
);

CREATE TABLE password_reset_token(
    password_reset_token_id BIGSERIAL,
    token VARCHAR(255) NOT NULL,
    expiry_date  TIMESTAMP,
    user_id BIGINT,
    CONSTRAINT FK_password_reset_tokens_users
        FOREIGN KEY (user_id) REFERENCES users(user_id),
    CONSTRAINT password_reset_token_pkey PRIMARY KEY(password_reset_token_id)
);


create table password_reset_token (password_reset_token_id bigint generated by default as identity, expiry_date timestamp, token varchar(255), user_id bigint not null, primary key (password_reset_token_id))
create table role (role_id bigint generated by default as identity, created_at timestamp, deleted boolean, enabled boolean, modified_at timestamp, name varchar(50), primary key (role_id))
create table user (user_id bigint generated by default as identity, created_at timestamp, deleted boolean, email varchar(255), enabled boolean, firstname varchar(255), last_login timestamp, last_password_reset_data timestamp, lastname varchar(255), modified_at timestamp, password varchar(255), primary key (user_id))
create table user_role (id bigint generated by default as identity, role_id bigint, user_id bigint, primary key (id))
alter table role add constraint UK_8sewwnpamngi6b1dwaa88askk unique (name)
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
table user_role add constraint UK872xec3woupu3gw59b04pj3sa unique (user_id, role_id)
alter table password_reset_token add constraint FK5lwtbncug84d4ero33v3cfxvl foreign key (user_id) references user
alter table user_role add constraint FKa68196081fvovjhkek5m97n3y foreign key (role_id) references role
alter table user_role add constraint FK859n2jvi8ivhui0rl0esws6o foreign key (user_id) references user